[build]
  command = "npm run build"
  publish = "dist/"

[template]
  incoming-hooks = ["Ghost"]

[[plugins]]
  package = "netlify-plugin-11ty"
  [plugins.inputs]
    cache_img = './img'
    cache_img_httpHeader = false

    cache_assets = '../.cache'
    cache_other = []
